# Generated by Django 5.2.7 on 2025-11-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок поста",
                        max_length=255,
                        verbose_name="Заголовок поста",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите содержание поста",
                        verbose_name="Содержание поста",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        upload_to="blog_posts/preview_images",
                        verbose_name="Превью изображение поста",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication_sign",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовать пост?",
                        verbose_name="Публикация поста",
                    ),
                ),
                (
                    "count_views",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Укажите количество просмотров поста",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог пост",
                "verbose_name_plural": "Блог посты",
                "ordering": ["-created_at"],
            },
        ),
    ]
