# Generated by Django 5.2.7 on 2025-11-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Введите название продукта",
                max_length=255,
                verbose_name="Название продукта",
            ),
        ),
    ]
