# Generated by Django 5.2.7 on 2025-11-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Отображать товар каталоге",
                verbose_name="Активный товар",
            ),
        ),
    ]
